- name: Create influxdb database
  shell: "influx
            -host '{{ influxdb_host }}'
            -ssl
            -port {{ influxdb_port }}
            -username {{ influxdb_admin_user }}
            -password {{ influxdb_admin_password }}
            -execute \"CREATE DATABASE {{ influxdb_database }}\""
  tags: sensors,influxdb

- name: Create influxdb user with R/W access
  shell: "influx
            -host '{{ influxdb_host }}'
            -ssl
            -port {{ influxdb_port }}
            -username {{ influxdb_admin_user }}
            -password {{ influxdb_admin_password }}
            -execute \"CREATE USER {{ influxdb_user }} WITH PASSWORD '{{ influxdb_password }}';
                       GRANT ALL ON {{ influxdb_database }} TO {{ influxdb_user }};\""
  tags: influxdb,sensors

- name: Create influxdb user for Grafana with READ-only access
  shell: "influx
            -host '{{ influxdb_host }}'
            -ssl
            -port {{ influxdb_port }}
            -username {{ influxdb_admin_user }}
            -password {{ influxdb_admin_password }}
            -execute \"CREATE USER grafana WITH PASSWORD '{{ grafana_password }}';
                       GRANT READ ON {{ influxdb_database }} TO grafana\""
  tags: influxdb,grafana,sensors

- name: Put the binary in place
  copy:
    src: "{{ playbook_dir }}/../sensors"
    dest: "/usr/local/bin/sensors"
    mode: "0755"
  become: true
  tags: sensors

- name: Create systemd service config
  template:
    src: "sensors.service.j2"
    dest: "/etc/systemd/system/sensors.service"
    mode: "0664"
  become: true
  tags: sensors,systemd

- name: Enable the service
  systemd:
    name: sensors
    enabled: true
  become: true
  tags: sensors,systemd

- name: Start the service
  systemd:
    name: sensors
    daemon_reload: true
    state: restarted
  become: true
  tags: sensors,systemd
