---
- name: Deploy the sensors bot
  hosts: all
  become: true
  gather_facts: false

  vars:
    service_binary: ../sensors

  roles:
    - role: suhlig.simple_systemd_service
      become: true
      vars:
        program:
          name: sensors
          description: Publishes sensor measurements to InfluxDB
          binary: "{{ service_binary }}"
          parameters:
            - "--influxdb-url https://{{ influxdb_host }}:{{ influxdb_port }}"
            - "--influxdb-database {{ influxdb_database }}"
            - "--influxdb-user {{ influxdb_user }}"
            - "--i2c-bus {{ i2c_bus }}"
            - "--bme280-address {{ bme280_address }}"
            - "{% if tsl2561_address is defined %}--tsl2561-address {{ tsl2561_address }}{% endif %}"
          environment:
            - "INFLUXDB_PASSWORD={{ influxdb_user_password }}"
#        deployment_event_url: "{{ influxdb_url }}"
      tags: [ sensor, gobot, temperature, celsius, humidity, percent, pressure, pascal, bme280, luminosity, lux, tsl2561, systemd, service ]
