---
- name: Deploy the sensors service
  hosts: all
  become: true
  gather_facts: true

  vars:
    service_binary: ../sensors

  roles:
    - role: suhlig.simple_systemd_service
      become: true
      vars:
        program:
          name: sensors
          description: Publishes sensor measurements to InfluxDB
          binary: "{{ service_binary }}"
          parameters:
            - "--influxdb-url https://{{ influxdb_host }}:{{ influxdb_port }}"
            - "--influxdb-database {{ influxdb_database }}"
            - "--influxdb-user {{ influxdb_user }}"
            - "--influxdb-password {{ influxdb_user_password }}"
            - "--i2c-bus {{ i2c_bus }}"
            - "--i2c-address {{ i2c_address }}"
          timer:
            - OnUnitActiveSec=1m
#        deployment_event_url: "{{ influxdb_url }}"
      tags: [ sensor, temperature, humidity, pressure, bme280, systemd, service ]
